# Generated by Django 3.0.2 on 2020-02-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200208_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标签'),
        ),
    ]
